# Generated by Django 6.0.3 on 2026-04-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStok',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('category_name', models.TextField(blank=True, db_column='Category_Name', null=True)),
                ('category_type', models.TextField(blank=True, db_column='Category_Type', null=True)),
            ],
            options={
                'db_table': 'Category_stok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Типа устройства взятого на мониторинг')),
            ],
            options={
                'verbose_name': 'Тип устройства взятого на мониторинг',
                'verbose_name_plural': 'Типы устройств взятых на мониторинг',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Тип устройства')),
            ],
            options={
                'verbose_name': 'Тип устройства',
                'verbose_name_plural': 'Типы устройств',
            },
        ),
        migrations.CreateModel(
            name='LocationOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(max_length=40, verbose_name='Регион')),
                ('branch', models.CharField(max_length=40, verbose_name='Филиал')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('street', models.CharField(max_length=60, verbose_name='Улица')),
                ('house', models.IntegerField(verbose_name='Дом')),
                ('room', models.IntegerField(verbose_name='Комната')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Заметка')),
            ],
            options={
                'verbose_name': 'Адреса локации',
                'verbose_name_plural': 'Адреса локаций',
            },
        ),
        migrations.CreateModel(
            name='TypeOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Тип локации')),
            ],
            options={
                'verbose_name': 'Тип офиса',
                'verbose_name_plural': 'Типы офисов',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('model', models.TextField(db_index=True, verbose_name='Модель устройства')),
                ('note', models.CharField(blank=True, max_length=60, verbose_name='Заметка по модели устройства')),
                ('device_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.devicemonitoring', verbose_name='Тип устройства взятого на мониторинг')),
                ('device_type_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.devicetype', verbose_name='Тип устройства')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.locationoffice', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Модель устройства',
                'verbose_name_plural': 'Модели устройств',
            },
        ),
        migrations.AddField(
            model_name='locationoffice',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.typeoffice', verbose_name='Тип локации'),
        ),
    ]
