# Generated by Django 6.0.3 on 2026-04-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='models',
            new_name='device_type_ref',
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.devicemonitoring', verbose_name='Тип устройства взятого на мониторинг'),
        ),
    ]
