# Generated by Django 6.0.3 on 2026-04-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_rename_models_devicemodel_device_type_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='note',
            field=models.CharField(blank=True, max_length=60, verbose_name='Заметка по модели устройства'),
        ),
    ]
