# Generated by Django 6.0.3 on 2026-04-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_devicemodel_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationoffice',
            name='note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заметка'),
        ),
    ]
