# Generated by Django 6.0.3 on 2026-06-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemName',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('problem_name', models.TextField(db_column='problem_name')),
            ],
            options={
                'db_table': 'zabbix_trigger_adm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=55, verbose_name='Тип оповещения о событии')),
            ],
            options={
                'verbose_name': 'Тип попвещений задач',
                'verbose_name_plural': 'Типы оповещений',
            },
        ),
        migrations.CreateModel(
            name='BranchRole',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('branch_code', models.CharField(max_length=8, verbose_name='код офиса')),
                ('branch_city_en', models.CharField(max_length=40, verbose_name='Город')),
                ('branch_name', models.CharField(max_length=40, verbose_name='Филиал')),
                ('branch_role_sop', models.CharField(max_length=50, verbose_name='Роль в Remedy СОП')),
                ('branch_code_sop', models.CharField(max_length=40, verbose_name='Код роли СОП')),
                ('branch_role_adm', models.CharField(max_length=50, verbose_name='Роль в Remedy админ')),
                ('branch_code_adm', models.CharField(max_length=40, verbose_name='Код роли админ')),
            ],
            options={
                'verbose_name': 'Role in Remedy',
                'verbose_name_plural': 'Roles in Remedy',
            },
        ),
        migrations.CreateModel(
            name='DateTimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_schedule', models.CharField(verbose_name='')),
                ('weekly_schedule', models.CharField(verbose_name='')),
                ('time_schedule', models.TimeField(verbose_name='')),
                ('start_date', models.DateField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Дата и время расписания',
                'verbose_name_plural': 'Даты и время расписаний',
            },
        ),
        migrations.CreateModel(
            name='NameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_schedule', models.CharField(max_length=50, verbose_name='')),
                ('description_schedule', models.TextField(verbose_name='Описание правила')),
            ],
            options={
                'verbose_name': 'Имя правила',
                'verbose_name_plural': 'Имена правил',
            },
        ),
        migrations.CreateModel(
            name='RulesSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rules', models.CharField(max_length=50, verbose_name='Выберите условие')),
                ('count_rules', models.IntegerField(null=True)),
                ('month_over_month', models.IntegerField(null=True)),
                ('week_over_week', models.IntegerField(null=True)),
                ('day_over_day', models.IntegerField(null=True)),
                ('device_type', models.CharField(blank=True, choices=[('adm', 'Триггеры рабочих мест адми'), ('sop', 'Триггеры рабочих мест СОП'), ('prn', 'Триггеры PRINT')], max_length=40, null=True, verbose_name='Источник триггеров')),
            ],
            options={
                'verbose_name': 'Правило расписания',
                'verbose_name_plural': 'Правила расписаний',
            },
        ),
        migrations.CreateModel(
            name='TextAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_action', models.TextField(verbose_name='Детальное описание')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create_schedule', models.CharField(default='', max_length=50, verbose_name='Инициатор правила')),
                ('action_schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generation.actionschedule', verbose_name='Тип оповещения планировщика')),
                ('date_time_schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generation.datetimeschedule', verbose_name='Расписание планировщика')),
                ('description_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.nameschedule', verbose_name='Описание условия планировщика')),
                ('rules_schedule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generation.rulesschedule', verbose_name='Выберите правило срабатывания планировщика')),
                ('text_action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='generation.textaction', verbose_name='Текст сообщения при срабатывании')),
            ],
            options={
                'verbose_name': 'Планировщик',
                'verbose_name_plural': 'Планировщики',
                'db_table': 'generation_scheduler',
            },
        ),
    ]
