# Generated by Django 6.0.3 on 2026-04-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStok',
            fields=[
                ('index', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('category_name', models.TextField(blank=True, db_column='Category_Name', null=True)),
                ('category_type', models.TextField(blank=True, db_column='Category_Type', null=True)),
            ],
            options={
                'db_table': 'Category_stok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=55, verbose_name='Тип оповещения о событии')),
            ],
            options={
                'verbose_name': 'Тип попвещений задач',
                'verbose_name_plural': 'Типы оповещений',
            },
        ),
        migrations.CreateModel(
            name='DateTimeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_schedule', models.CharField(verbose_name='')),
                ('weekly_schedule', models.CharField(verbose_name='')),
                ('time_schedule', models.TimeField(verbose_name='')),
                ('start_date', models.DateField(verbose_name='')),
            ],
            options={
                'verbose_name': 'Дата и время расписания',
                'verbose_name_plural': 'Даты и время расписаний',
            },
        ),
        migrations.CreateModel(
            name='NameSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_schedule', models.CharField(max_length=50, verbose_name='')),
                ('description_schedule', models.TextField(verbose_name='Условие запуска')),
            ],
            options={
                'verbose_name': 'Имя правила',
                'verbose_name_plural': 'Имена правил',
            },
        ),
        migrations.CreateModel(
            name='RulesSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rules', models.CharField(max_length=50, verbose_name='Выберите условие')),
            ],
            options={
                'verbose_name': 'Правило расписания',
                'verbose_name_plural': 'Правила расписаний',
            },
        ),
        migrations.CreateModel(
            name='TextAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_action', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Тип действия',
                'verbose_name_plural': 'Типы действий',
            },
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_create_schedule', models.CharField(default='', max_length=50, verbose_name='Инициатор правила')),
                ('action_schedule', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='generation.actionschedule', verbose_name='Тип оповещения планировщика')),
                ('date_time_schedule', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='generation.datetimeschedule', verbose_name='Расписание планировщика')),
                ('description_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generation.nameschedule', verbose_name='Описание условия планировщика')),
                ('rules_schedule', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='generation.rulesschedule', verbose_name='Выберите правило срабатывания планировщика')),
                ('text_action', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='generation.textaction', verbose_name='Текст сообщения при срабатывании')),
            ],
            options={
                'verbose_name': 'Планировщик',
                'verbose_name_plural': 'Планировщики',
                'db_table': 'generation_scheduler',
            },
        ),
    ]
