# Generated by Django 6.0.3 on 2026-04-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='text_action',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='generation.textaction', verbose_name='Текст сообщения при срабатывании'),
        ),
    ]
